### ISSUE TITLE
Text annotation only works in the direction of reading

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/annolite#11]
Apparently, it is impossible to highlight tokens in `annotate()` from right to left (or against the direction of reading)

Using the example from the vignette:
```
library(polmineR)
library(annolite)


annotab <- annotate(
  secretary_general_2000_speech,
  secretary_general_2000_annotations,
  buttons = list(vision = "green", dystopia = "pink")
)
```

If you draw the mouse in the direction of reading, the pop up menu appears, the text is highlighted and everything is fine, but if you draw the mouse in the opposite direction, the menu still shows up but the text isn't highlighted. However, the invisibly annotated passages are actually passed to the annotab data.frame.

**Comment by ablaette** [comment]
Thanks for describing the problem so accurately. A new version on the dev branch fixes the issue. Annotating from right to left would cause a JavaScript crash, because my code would have tried to iterate from the first larger position to the lower position, which is not possible.
