### ISSUE TITLE
Check if object is annotationtable is missing negation

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/annolite#12]
There is a check if an object "x" is NOT a annotationtable, but if I am not mistaken the check if the wrong way around, i.e. missing a "!". 

https://github.com/PolMine/annolite/blob/fe43fa2d99e121dba5e965c3844a43a311622d8e/R/annotationstable.R#L80-L83

**Comment by ablaette** [comment]
Perfectly true, stupid mistake, solved when addressing [issue # 13](https://github.com/PolMine/annolite/issues/13)
