### ISSUE TITLE
Check if columns "text" and "annotation" are NA in annotationtable leads to unjustified warnings

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/annolite#13]
I modified an example from the annolite vignette to illustrate that when reading annotations from a csv file, both the columns "text" (not in the example file, but this happens when you just click on a term to annotate it) and "annotation" might include NA values which shouldn't make the annotationtable object invalid:

```
library(polmineR)
library(annolite)
tmp <- tempdir()
write.csv(secretary_general_2000_annotations, sprintf("%s/temp_annotation.csv", tmp))
annotab <- annotate(
  secretary_general_2000_speech,
  annotations = read.csv(sprintf("%s/temp_annotation.csv", tmp)),
  buttons = list(vision = "green", dystopia = "pink")
)
```

The warning 

> Warning messages:
1: In is.annotationstable(x) :
  Object is not a valid 'annotationstable' object, column 'annotation' includes NA values.
2: In as.annotationstable(annotations) :
  Input object x cannot be transformed to a (valid) 'annotationstable' object.

is triggered when executing annotate() and closing the annotation with "Done" without adding another annotation.

**Comment by ablaette** [comment]
Clearly the code of `as.annotationstable()` was not mature. In a new *annolite* version (dev branch), `as.annotationstable()`  will turn NA values in the column "anntations" into "".

I simplified you example somewhat and included it as a unit test as follows:

```r
library(annolite)
outfile <- tempfile()
write.csv(secretary_general_2000_annotations, file = outfile)
x <- read.csv(file = outfile)
is.annotationstable(as.annotationstable(x))
```
