### ISSUE TITLE
Check if path in file argument of annotate actually exists

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/annolite#6]
The `annotate()` method takes a `file` argument in which a path to a csv file can be stated in which the annotations are stored even in case something goes wrong (i.e. something crashes). However, it does not check whether or not the path actually exists, leading to a crash (it says its a warning but the shiny app is gone after that) after the first annotation. 

> Warning: Error in file: cannot open the connection

I assume this could be easily avoided using a `dir.exists()` of some sort and issuing a friendlier reminder to actually state an existing path?

**Comment by ablaette** [comment]
Very good point. I included the following safeguard into the `annotate()` function. 

```r
if (isFALSE(is.null(file))){
  if (isFALSE(dir.exists(dirname(file))))
    stop(sprintf("Cannot use file '%s' to store annotations: Directory '%s' does not exist.", file, dirname(file)))
} 
```

Depending on the length of the filename, the error may throw a lot of red ink, but the message should be telling for those who read error messages.

The code I used to check whether things work as intended:

```r
library(annolite)
library(polmineR)
use("polmineR")
sc <- corpus("REUTERS") %>% subset(id == "127")

outdir <- file.path(tempdir(), "abcd")
dir.create(outdir)

outfile1 <- file.path(outdir, "tmp_anno.rds")
y <- annotate(sc, file = outfile1) 
file.exists(outfile1) # works only if you have created an annotation

outfile2 <- file.path(tempdir(), "abcz", "tmp_anno.rds")
y <- annotate(sc, file = outfile2) # throws error
```
